MODULE ebs_typs
USE MATH
 IMPLICIT NONE

                                                                     
 TYPE :: BAND 
   INTEGER :: PATH = 0
   INTEGER :: SPN = 1
   INTEGER :: NKPT = 0
   INTEGER :: BND = 0
   REAL(KIND=DP) :: K = 0.0_DP            !K => KPOINTDISTANCE
   REAL(KIND=DP) :: E = 0.0_DP            !E>ENERGY
   REAL(KIND=DP) :: W = 0.0_DP            !W> BLOCH CHARACTER
   REAL(KIND=DP), DIMENSION(:),ALLOCATABLE :: OC
   LOGICAL :: LOCU = .FALSE.                !OCUPATION
 END TYPE BAND

 TYPE :: GRID
   REAL(KIND=DP) :: DIST  !KPOINTDISTANCE
   REAL(KIND=DP),DIMENSION(3) :: A  !REC VEKTOR
   REAL(KIND=DP),DIMENSION(3) :: B  !REC VEKTOR
 END TYPE GRID


 TYPE :: FILENUMBERS
  INTEGER :: NK, KPTS, IKPTS, ORBIT, BND, IONS, SPIN
  LOGICAL :: SLIMPRJ, OLDPRO
 END TYPE FILENUMBERS

 TYPE :: NUMBERS
   INTEGER :: PATH, BAND, ORB, TKPTS, TCOL, SAMEK
   INTEGER,DIMENSION(2) :: FIT=0, SPEC=0
   LOGICAL,DIMENSION(2) :: SPECDAT=.FALSE.
   REAL(KIND=DP),DIMENSION(2) :: EPMIN=1000.0_DP,ENMAX=-1000.0_DP
   LOGICAL,DIMENSION(2) :: LEPMIN=.FALSE.,LENMAX=.FALSE.
 END TYPE NUMBERS

 TYPE :: PARAMETERS
   INTEGER :: POINTS, FORB, IREFLECT, FGRID, SPN, NSION
   INTEGER,DIMENSION(2) :: KSKIP,SION=(/ 0, 0 /)
   REAL(DP) :: TRASH, EDIF, EGAP, DBLOCH
   REAL(DP) :: EFERMI,  ODISTINCT, EPS, DGRAD
   REAL(DP) :: SIGMA,SPECDELTA
   REAL(DP),DIMENSION(2) :: FBORDER,WDIF
   REAL(KIND=DP), DIMENSION(2,3) :: SYMPOINTS
   CHARACTER(LEN=20),DIMENSION(:),ALLOCATABLE :: ORBNAMES
   LOGICAL :: BAND=.TRUE.,BANDPLOT=.TRUE.,ROOTSCALC=.TRUE.,LSURFACE
   LOGICAL :: POLY=.FALSE.,LBAV=.FALSE.,LOAV=.TRUE.,NORM=.FALSE.
   LOGICAL :: SPECFUN=.TRUE.,SYMREC=.TRUE.,SLIMSPEC=.TRUE.,MULTIFERMI=.FALSE.
 END TYPE PARAMETERS


 TYPE :: SYMMETRY
   REAL(DP),DIMENSION(2,2) :: S2D
   REAL(DP),DIMENSION(2,3) :: ASYM,BSYM
 END TYPE SYMMETRY


END MODULE ebs_typs
